# Generated by Django 5.2.15 on 2026-09-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0124_totpdevice_recoverycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='frontmatter',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='fileasset',
            name='entity_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
